commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /

communaute:
    resource: "@CommunauteBundle/Resources/config/routing.yml"
    prefix:   /

produits:
    resource: "@ProduitsBundle/Resources/config/routing.yml"
    prefix:   /

p_lants:
    resource: "@PLantsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
